<div class="modal fade" id="stageDeletionModal" tabindex="-1" role="dialog" aria-labelledby="nextStageModalLabel" aria-hidden="true">
    <div class="vertical-alignment-helper" >
    <div class="modal-dialog vertical-align-center" role="document">
        <div class="modal-content">
            <div class="modal-body row text-center">
                <h3>Are you sure you want to unlock this stage?</h3>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" id="stageDeletionModalYes" >Yes</button>
                <button type="submit" class="btn btn-danger" id="stageDeletionModalCancel">Cancel</button>
            </div>
        </div>
    </div>
    </div>
    </div>
</div>
