
<div class="modalContainer">
        <div class="modalMain container ">
            <div class="modal-body">
                <h3>Are you sure you want to remove the lock?</h3>
            </div>
            <div class="modalFooter btn-toolbar ">
                <button type="submit" class="btn btn-primary col-sm-2">Yes</button>
                <button type="submit" class="btn btn-danger col-sm-2 " >Cancel</button>
            </div>
        </div>
</div>

//split buttons
//display modal at right height
//round modal corners
