<div class="modal fade" id="applicantPassword" tabindex="-1" role="dialog" data-backdrop="static"
     data-keyboard="false" aria-labelledby="applicantPasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="passwordElements"> Applicant's platform created: </h3>
                <a class="passwordElements" target="_blank"
                   data-href="http://<?php echo $_SERVER['HTTP_HOST'] . '/public/'?>"
                   id="applicant_password_link"><?php echo $_SERVER['HTTP_HOST'] . '/public/'?><span></span></a>
                <hr>
                <form id="generate_password" method="post">
                    <div class="form_pass">
                        <label class="passwordElements" for="randomPassword">Password:</label>
                        <input type="text" id="randomPassword" class="form-control passwordElements" readonly value="">
                        <button class="passwordElements" id="copyPassword" type="button">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-clipboard" viewBox="0 0 16 16">
                                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0
                                0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                                <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1
                                .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11
                                2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                            </svg>
                        </button>
                    </div>
                    <div class="div_pass">
                        <label for="password_checkbox" class="password_checkbox passwordElements">
                            Confirm saving the password
                        </label>
                        <input type="checkbox" id="password_checkbox" class="btn btn-success passwordElements" required>
                    </div>
                    <div id="passwordMessage" class="alert"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btnPasswordGenerate">Confirm</button>
            </div>
        </div>
    </div>
</div>
