
<div class="modal fade" id="applicantModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">
                    Applicant Details
                    <span id="apprentice" class="label label-warning"></span>
                    <span class="pull-right" id="dateTimeAdded"></span>
                </h2>
            </div>
            <div id="modal-main">
                <div class="modal-body">
                    <section>
                        <h4>Personal Information</h4>
                        <p class="detail">Name: <span id="name"></span></p>
                        <p class="detail">Email: <span id="email"></span></p>
                        <p class="detail">Phone Number: <span id="phoneNumber"></span></p>
                    </section>
                    <section>
                        <h4>Application Info</h4>
                        <p class="detail">Stage: <span id="stageName"></span></p>
                        <p class="detail" id="stageOptionNameContainer">Stage Option: <span id="stageOptionName"></span></p>
                        <p class="detail">Cohort: <span id="cohortDate"></span></p>
                        <p class="detail">Background Info:</p>
                        <p id="backgroundInfo"></p>
                        <p class="detail">Reason for wanting to be a dev:</p>
                        <p id="whyDev"></p>
                        <p class="detail">Code Experience:</p>
                        <p id="codeExperience"></p>
                        <p class="detail">Heard About Us: <span id="hearAbout"></span></p>
                        <p class="detail" id="eligible"></p>
                        <p class="detail" id="eighteenPlus"></p>
                        <p class="detail">Finance: <span id="finance"></span></p>
                        <p class="detail">Notes:</p>
                        <p id="notes"></p>
                    </section>
                    <section>
                        <h4>Taster session</h4>
                        <p class="detail">Taster session: <span id="taster"></span></p>
                        <p class="detail" id="tasterAttendance"></p>
                    </section>
                    <section>
                        <h4>Assessment</h4>
                        <p class="detail">Assessment day: <span id="assessmentDay"></span></p>
                        <p class="detail">Assessment Time: <span id="assessmentTime"></span></p>
                        <p class="detail">Aptitude Score: <span id="aptitude"></span></p>
                        <p class="detail">Diversitech: <span id="diversitechInterest"></span></p>
                        <p class="detail">Chosen Course Date: <span id="chosenCourseDatePretty"></span></p>
                        <p class="detail">Assessment notes:</p>
                        <p id="assessmentNotes"></p>
                    </section>
                    <section class="student">
                        <h4>Onboarding Info</h4>
                        <p class="detail">Diversitech amount: <span id="diversitech"></span></p>
                        <p class="detail">EdAid amount: <span id="edaid"></span></p>
                        <p class="detail">Upfront amount: <span id="upfront"></span></p>
                        <p class="detail">Laptop required: <span id="laptop"></span></p>
                        <p class="detail">Laptop deposit paid: <span id="laptopDeposit"></span></p>
                        <p class="detail">Laptop number: <span id="laptopNum"></span></p>
                        <p class="detail">Kit collection date: <span id="kitCollectionDay"></span></p>
                        <p class="detail">Kit collection time: <span id="kitCollectionTime"></span></p>
                        <p class="detail">Kit number: <span id="kitNum"></span></p>
                        <p class="detail">Team: <span id="team"></span></p>
                    </section>
                    <section class="student">
                        <h4>Student Info</h4>
                        <p class="detail">Github Username: <span id="githubUsername"></span></p>
                        <p class="detail">Portfolio Url: <span id="portfolioUrl"></span></p>
                        <p class="detail">Plesk Hosting Url: <span id="pleskHostingUrl"></span></p>
                        <p class="detail">Github Education Link: <span id="githubEducationLink"></span></p>
                        <p class="detail">Profile Link: <a id="userProfileLink" href="userProfileLink" target="_blank"></a>
                            <button class="clipboard">
                                <i class="glyphicon glyphicon-copy"></i>
                            </button>
                        </p>
                        <p class="detail">Notes:</p>
                        <p id="additionalNotes"></p>
                    </section>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
