<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

<div class="modal fade" id="applicantPassword" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" aria-labelledby="applicantPasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="passwordElements"> Applicant's platform created: </h3><a class="passwordElements" target="_blank" href="http://<?php echo $_SERVER['HTTP_HOST'] . '/public/'?>" id="applicant_password_link"><?php echo $_SERVER['HTTP_HOST'] . '/public/'?></a>
                <hr>
                <form id="generate_password" method="post">
                    <div class="form_pass">
                        <label class="passwordElements" for="randomPassword">Password:</label>
                        <input type="text" id="randomPassword" class="form-control passwordElements" readonly value=""><button class="passwordElements" id="copyPassword" type="button"><i class="bi bi-clipboard"></i></button>
                    </div>
                    <div class="div_pass">
                        <label for="password_checkbox" class="password_checkbox passwordElements">Confirm saving the password</label>
                        <input type="checkbox" id="password_checkbox" class="btn btn-success passwordElements" required>
                    </div>
                    <div id="passwordMessage" class="alert"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btnPasswordGenerate">Confirm</button>
            </div>
        </div>
    </div>
</div>
