<div id="calendarModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
                <h3 class="modal-title">Event Details</h3>
            </div>
            <div id="modalBody" class="modal-body">
                <h4>Event Details</h4>
                <p class="detail">Event: <span id="eventName"></span></p>
                <p class="detail">Location: <span id="eventLocation"></span></p>
                <p class="detail">Start: <span id="eventStart"></span></p>
                <p class="detail">End: <span id="eventEnd"></span></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>