<!--<button type="button" id="calendarEventModal" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>-->

<!-- Modal -->
<dialog id="myModal" class="modal-lg" data-toggle="modal" data-bs-target="#myModal">


            <!-- Modal content-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" id="close">&times;</button>
                    <h2 class="modal-title">Event Details</h2>
                </div>
                <div id="modal-main">
                    <div id="modal-main" class="modal-body">
                        <h3>Event Details:</h3>
                        <h5 id="eventName">Event name: </h5>
                        <h5 id="eventLocation">Location: </h5>
                        <h5 id="eventDate">Date: </h5>
                        <h5 id="eventStart">Start: </h5>
                        <h5 id="eventEnd">End: </h5>
                    </div>
                </div>
            </div>

</dialog>