

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Company Details</h2>
            </div>
            <div id="modal-main">
                <div id="modal-main" class="modal-body">
                    <h3>Company Details</h3>
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Size</th>
                            <th scope="col">Tech Stack</th>
                            <th scope="col">Postcode</th>
                            <th scope="col">Phone number</th>
                            <th scope="col">Website URL</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><p id="name"></p></td>
                            <td><p id="size"></p></td>
                            <td><p id="tech_stack"></td>
                            <td><p id="postcode"></p></td>
                            <td><p id="phone_number"></p></td>
                            <td><p id="url_website"></p></td>
                        </tr>
                        </tbody>
                    </table>
                    <h3>Company Contacts</h3>
                    <div id="contacts"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
