<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Applicant Details</h2>
            </div>
            <div id="modal-main">
                <div class="modal-body">
                    <h3>Company Details</h3>
                    <h4> Name</h4>
                    <p id="name"></p>
                    <h4>Size</h4>
                    <p id="size"></p>
                    <h4>Tech Stack</h4>
                    <p id="tech_stack"></p>
                    <h4>Postcode</h4>
                    <p id="postcode"></p>
                    <h4>Phone number</h4>
                    <p id="phone_number"></p>
                    <h4>Website URL</h4>
                    <p id="url_website"></p>
                </div>

<!--                //-->
<!--                -->
<!--                <hr>-->
<!--                <div class="modal-body">-->
<!--                    <h3>Application Information</h3>-->
<!--                    <h4>Cohort</h4>-->
<!--                    <p id="cohortDate"></p>-->
<!--                    <h4>Reason for wanting to be a dev</h4>-->
<!--                    <p id="whyDev"></p>-->
<!--                    <h4>Code Experience</h4>-->
<!--                    <p id="codeExperience"></p>-->
<!--                    <h4>Heard About Us</h4>-->
<!--                    <p id="hearAbout"></p>-->
<!--                    <h4>Eligibility</h4>-->
<!--                    <p id="eligible"></p>-->
<!--                    <h4>18+ </h4>-->
<!--                    <p id="eighteenPlus"></p>-->
<!--                    <h4>Finance</h4>-->
<!--                    <p id="finance"></p>-->
<!--                    <h4>Notes</h4>-->
<!--                    <p id="notes"></p>-->
<!--                    <h4>Date/Time Added</h4>-->
<!--                    <p id="dateTimeAdded"></p>-->
<!--                </div>-->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
