<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Company Details</h2>
            </div>
            <div id="modal-main">
                <div class="modal-body">
                    <h3>Company Details</h3>
                    <h4> Name</h4>
                    <p id="name"></p>
                    <h4>Size</h4>
                    <p id="size"></p>
                    <h4>Tech Stack</h4>
                    <p id="tech_stack"></p>
                    <h4>Postcode</h4>
                    <p id="postcode"></p>
                    <h4>Phone number</h4>
                    <p id="phone_number"></p>
                    <h4>Website URL</h4>
                    <p id="url_website"></p>
                    <h3>Company Contacts</h3>
                    <div id="contacts"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
