
<!-- Modal -->
<div class="modal fade" id="deleteCourseModal" tabindex="-1" role="dialog" aria-labelledby="deleteCourseModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="deleteCourseModal">Delete Course Options</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid" id="deleteCourseInfo">
                    <div class="row">
                        <div id="studentNamesContainer" class="col-xs-4"></div>
                        <div id="reassignContainer" class="col-xs-4">
                            <h4>Reassign Student</h4>
                            <form id="DeleteCoursesForm" method="post"></form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="d-flex flex-column">
                    <button type="submit" class="btn btn-danger" value="Delete" form='DeleteCoursesForm'>DELETE</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
                <div id="nextStageSaveButtonContainer" class="col-xs-2"></div>
            </div>
        </div>
    </div>
</div>
