<div class="row">
    <div class="col-xs-8 center-block">
        <button class="btn btn-primary pull-right" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Apply Filters
        </button>
        <div class="collapse" id="collapseExample">
            <div class="well">
                <label for="daterange">Application Date</label>
                <input type="text" name="daterange" value="01/01/2018 - 01/15/2018" />
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Cohort Date
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                    </ul>
                </div>
                <button class="btn btn-primary apply" type="button">
                    Apply
                </button>
            </div>
        </div>
    </div>
</div>