    <div class="row">
        <div class="col-xs-8 center-block">
            <button class="btn btn-primary pull-right" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Apply Filters
            </button>
            <div class="collapse" id="collapseExample">
                <div class="well">
                    ...
                </div>
            </div>
        </div>
    </div>

