<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Applicant Details</h2>
            </div>
            <div id="modal-main">
                <div class="modal-body">
                    <h3>Personal Information</h3>
                    <h4> Name</h4>
                    <p id="name"></p>
                    <h4> Job Title</h4>
                    <p id="job_title"></p>
                    <h4>Email</h4>
                    <p id="email"></p>
                    <h4>Phone Number</h4>
                    <p id="phone"></p>
                    <h4>Primary Contact?</h4>
                    <p id="is_primary_contact"></p>
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
