
<!-- Modal -->
<div class="modal fade" id="nextStageModal" tabindex="-1" role="dialog" aria-labelledby="nextStageModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="nextStageModalLabel">Next Stage Options</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <section>
                    <h4>Booked Into Assessment Day Options</h4>
<!--                    --><?php //$stageModel = $container['StageModel'](); ?>
                    <select name="next-stage-options" id="next-stage-options">
                        <option value="test">test</option>
                        <option value="test">test</option>
                        <option value="test">test</option>
                        <option value="test">test</option>
                    </select>
                </section>
            </div>
            <div id="stage-options">Hifgdfgdfhsfgh</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
