
<div class="modal fade" id="nextStageModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">
                    Applicant Details
                    <span id="apprentice" class="label label-warning"></span>
                    <span class="pull-right" id="dateTimeAdded"></span>
                </h2>
            </div>
            <div id="modal-main">
                <div class="modal-body">
                    <section>
                        <h4>Booked Into Assessment Day Options</h4>
                        <p class="detail">Accepted Place <span id="name"></span></p>
                        <p class="detail">Rejected Place <span id="email"></span></p>
                        <p class="detail">Deferred Place <span id="phoneNumber"></span></p>
                    </section>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
