<?php
use Portal\Controllers\FrontEnd\StudentPasswordModalControllerFactory;
?>
<script src='js/nextStageModal.js' defer></script>
<script src='js/editApplicant.js' defer></script>

<div class="modal fade" id="studentPasswordModal" tabindex="-1" role="dialog" aria-labelledby="studentPasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="studentPasswordModalLabel">Successfully onboarded</h5>
            </div>
            <div class="modal-body">
                <section>
                <div class="form-group">
                    <label for="randomPassword">Student profile password:</label>
                    <input type="text" id="randomPassword" class="form-control" readonly value="<?php echo $password;?>">
                    <label for="copied-password-check">Please confirm you have copied the student's password</label>
                    <input type="checkbox" id="copied-password-check"/>
                    <p id="passwordCheckWarning"></p>
                </div>
                </section>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary btnOk">OK</button>
            </div>
        </div>
    </div>
</div>