<!DOCTYPE html>
<html>
<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('404');
    ?>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>
<main>
    <div class="container">
        <div class="alert alert-info">
            404 Page Not Found
        </div>
    </div>
</main>

<?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>
