<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Hiring Partners');
    ?>
    <link href="css/hiringPartner.css" rel="stylesheet" type="text/css">
    <script defer src="./js/validations.js"></script>
    <script defer src='./js/hiringPartner.js'></script>
    <script defer src='./js/hiringPartnerModal.js'></script>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>
        <h3>Add new hiring partner</h3>
        <form id='add-hiring-partner-form'>
            <label for="company-name">Company Name:</label>
            <input id="company-name" name="company-name" class="submit-hiring-partner form-control" type="text" placeholder="name">
            <label for='company-size'>Company Size:</label>
            <select name='company-size' id='company-size' class='submit-hiring-partner form-control'>
                <option value='0'>Please select a company size...</option>
                <?php echo \Portal\ViewHelpers\CompanySizeViewHelper::companySizeDropdown($data); ?>
            </select>
            <label for="company-tech-stack">Company Tech Stack:</label>
            <input id="company-tech-stack" name="company-tech-stack" class="submit-hiring-partner form-control" type="text" placeholder="Company tech stack">
            <label for='company-postcode'>Postcode:</label>
            <input id='company-postcode' name='company-postcode' class="submit-hiring-partner form-control" type="text" placeholder="Postcode">
            <label for='company-phone-number'>Phone Number:</label>
            <input id='company-phone-number' name='company-phone-number' class="submit-hiring-partner form-control" type="text" placeholder="Phone Number">
            <label for='company-url'>Company Website URL:</label>
            <input id='company-url' name='company-url' class="submit-hiring-partner form-control" type="text" placeholder="Company Website Url">
            <input id="submit-hiring-partner" type="submit" class="btn btn-success"/>
            <div id='add-hiring-partner-messages'></div>
        </form>
    <div class="container">
        <h1>Add contact to Hiring partner</h1>
        <form id='add-contact-form'>
            <label for='company'>Company:</label>
            <select name='company' id='company' class='submit-contact form-control'>
                <option value='0'>Please select a company</option>
                <?php echo \Portal\ViewHelpers\SelectCompanyViewHelper::selectCompanyDropdown($data); ?>
            </select>
            <label for="contact-name">Name:</label>
            <input id="contact-name" name="contact-name" class="submit-contact form-control" type="text" placeholder="Contact Name">
            <label for='contact-email'>eMail:</label>
            <input id='contact-email' name='contact-email' class="submit-contact form-control" type="text" placeholder="email">
            <label for='contact-job-title'>Job Title:</label>
            <input id='contact-job-title' name='contact-job-title' class="submit-contact form-control" type="text" placeholder="Job title">
            <label for='contact-phone-number'>Contact Phone Number:</label>
            <input id='contact-phone-number' name='contact-phone-number' class="submit-contact form-control" type="text" placeholder="Phone Number">
            <div class="contact-is-primary">
                <input class="form-check-input" type="checkbox" value="" id="contact-is-primary">
                <label class="form-check-label" for="contact-is-primary">Primary Contact</label>
            </div>
            <input id="submit-hiring-partner-contact" type="submit" class="btn btn-success"/>
            <div id='add-contact-messages'></div>
        </form>
    </div>
    <h3>Current Hiring Partners</h3>
    <div id='companies'></div>
        <!-- Modal -->
        <?php require('partials/companyDetailsModal.phtml'); ?>

<?php require 'partials/layout/footer.phtml'; ?>
</body>