<!DOCTYPE html>
<html lang="en">

<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Add Trainers');
    ?>
    <script defer src="./js/utils.js"></script>
    <script defer src="./js/validations.js"></script>
    <script defer src='./js/addTrainer.js'></script>
</head>
<body>
    <?php require 'partials/layout/header.phtml'; ?>
    <?php require 'partials/layout/nav.phtml'; ?>
    <h1>Add Trainers</h1>       
    <form>
        <label for="trainer-name">Trainer Name</label>
        <input name="name" class="create-trainer form-control" type="text" placeholder="Full Name" data-required="true" data-max='255' maxlength="255"/>
        <div id="nameError" class="alert hidden formItem_alert"></div>

        <label for="email">Email</label>
            <input id="email" name="email" class="create-trainer form-control" type="text" placeholder="email" data-required="true">
        <div id="emailError" class="alert hidden formItem_alert"></div>

        <label for="trainer-notes">Notes</label>
        <textarea name="notes" class="create-trainer form-control" placeholder="Notes" data-max="5000" maxlength="5000"></textarea>
        <div id="notesError" class="alert hidden formItem_alert"></div>

        <input type="submit" class="btn btn-success" />
    </form>
    <div id="messages" class="alert"></div>
    <?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>