<!DOCTYPE html>
<html>
    <head>
        <?php
        require 'partials/layout/head.phtml';
        echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Admin Panel');
        ?>
        <link rel="stylesheet" href="./css/admin.css">
    </head>
    <body>
        <?php require 'partials/layout/header.phtml'; ?>

            <main>
                <div class="row">
                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <a href="./applicants" class="custom-button">Applicants</a>
                    </div>

                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <a href="./events" class="custom-button">Events</a>
                    </div>

                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <a href="./hiringPartners" class="custom-button">Hiring Partners</a>
                    </div>

                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <a href="./addapplicant" class="custom-button">New Applicant</a>
                    </div>

                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <a href="#" class="custom-button">New Event</a>
                    </div>

                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <a href="#" class="custom-button">New Hiring Partner</a>
                    </div>

                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <a href="./editStages" class="custom-button">Edit Applicant Stages</a>
                    </div>

                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <a href="#" class="custom-button">Past Events</a>
                    </div>

                    <div class="col-xs-12 col-md-6 col-lg-4">
                        <a href="#" class="custom-button">New Hiring Partner Contact</a>
                    </div>

                </div>

            </main>

        <?php require 'partials/layout/footer.phtml'; ?>
    </body>
</html>
