<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>AcademyPortal | Admin</title>
        <link rel="stylesheet" type="text/css" href="css/genericStyles.css"/>
        <link rel="stylesheet" href="css/admin.css">
    </head>
    <body>
        <h1> Admin Page</h1>
        <a href="./register" class="custom-button">Add User</a>
        <a href="./addapplicant" class="custom-button">Register Applicant</a>
        <a href="./displayApplicants" class="custom-button">Display Applicants</a>
        <a href="./displayHiringPartnerPage" class="custom-button">Hiring Partners</a>
        <a href="./displayEventsPage" class="custom-button">Events</a>
    </body>
</html>
