
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Academy Portal | New Applicant</title>
    <link type="text/css" rel="stylesheet" href="./css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="./css/genericStyles.css">
    <script src="./js/validations.js" defer></script>
    <script src="./js/addApplicant.js" defer></script>
    <script src="./js/saveApplicant.js" defer></script>
</head>
<body>
    <div class="container">
        <h1>New Applicant Registration</h1>
        <form>
            <label for="name">Applicant Name</label>
            <div id="nameError" class="alert hidden formItem_alert"></div>
            <input id="name" name="name" class="submitApplicant form-control" type="text" placeholder="name" value="<?php echo $applicantName ?>" required>

            <label for="email">Applicant Email</label>
            <div id="emailError" class="alert hidden formItem_alert"></div>
            <input id="email" name="email" class="submitApplicant form-control" type="email" placeholder="email" value="<?php echo $applicantEmail ?>" required>

            <label for="phone">Applicant Phone Number</label>
            <div id="phoneError" class="alert hidden formItem_alert"></div>
            <input id="phone" name="phoneNumber" class="submitApplicant form-control" type="text" placeholder="phone number" value="<?php echo $applicantPhoneNumber ?>" required>

            <label for="cohorts">When would you like to join us?</label>
            <select id="cohorts" class="submitApplicant form-control" name="cohortId"  required>
                <option selected value="<?php echo $applicantCohortDate ?>"><?php echo $applicantCohortDate ?></option>
            </select>

            <label for="why-developer">Why do you want to become a software developer?</label>
            <div id="whyDevError" class="alert hidden formItem_alert"></div>
            <textarea id="why-developer" name="whyDev" class="submitApplicant form-control" placeholder="Enter here" required><?php echo $applicantWhyDev ?></textarea>

            <label for="experience">Please tell us about any relevant coding experience.</label>
            <div id="codeExperienceError" class="alert hidden formItem_alert"></div>
            <textarea id="experience" name="codeExperience" class="submitApplicant form-control" placeholder="Enter here"><?php echo $applicantCodeExperience ?></textarea>

            <label for="hear-about">How did you hear about Mayden Academy?</label>
            <select id="hear-about" class="submitApplicant form-control" name="hearAboutId" required>
                <option selected value="<?php echo $applicantHearAbout ?>"><?php echo $applicantHearAbout ?></option>
            </select>

            <div class="form-group">
                <input class="submitApplicant" name="eligible" type="checkbox" <?php echo $appicantIsEligable ? "checked" : ""; ?> />
                <label for="uk-eligible">I confirm I am eligible to study in the UK.</label>
            </div>

            <div>
                <input class="submitApplicant" name="eighteenPlus" type="checkbox" <?php echo $appicantEighteenPlus ? "checked" : ""; ?> />
                <label for="is-18">I confirm I will be at least 18 years before my chosen cohort*.</label>
            </div>

            <div class="form-group">
                <input class="submitApplicant" name="finance" type="checkbox" <?php echo $appicantFinance ? "checked" : ""; ?> />
                <label for="finance">I would like to apply for interest free finance.</label>
            </div>

            <label for="notes">Notes.</label>
            <div id="notesError" class="alert hidden formItem_alert"></div>
            <textarea id="notes" name="notes" class="submitApplicant form-control" placeholder="Enter here" required><?php echo $applicantNotes ?></textarea>

            <input id="submitApplicant" type="submit" class="btn btn-success"/>
            <div id="generalError" class="alert alert-danger hidden formItem_alert"></div>
        </form>
        <a href="./admin" class="btn btn-success">Go back to the Admin Page</a>
    </div>
</body>
</html>
