<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Applicants');
    ?>
    <link rel="stylesheet" type="text/css" href="./css/style.css">
    <script src="./js/populateDropdowns.js" defer></script>
    <script defer src="./js/applicantModal.js"></script>
    <script defer src="./js/deleteApplicant.js"></script>
    <script defer src="./js/displayApplicants.js"></script>
    <script defer src="./js/nextStageModal.js"></script>
</head>
<body> 
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>

    <div class="row">
        <div class="col-xs-12 registeredApplicants">
            <h1>Applicants</h1>
            <form class="arrowForm" id="sortFilterApplicants" method="get">
                <ul class="nav nav-tabs" role="tablist">
                        <?php
                            foreach($data['applicantTabs'] as $applicantTab) {
                                echo '<li role="presentation" class="'. $applicantTab['name'] . '" id="' . $applicantTab['name'] . '-tab-button">' .
                                '<a href="#' . $applicantTab['name'] . '" aria-controls="' . $applicantTab['name'] . '" role="tab" data-toggle="tab">' . $applicantTab['displayName'] . '</a>' .
                                '</li>';
                            }
                        ?>
                    <li>
                        <div class="input-group rounded searchForm">
                            <input type="search" class="form-control rounded submitApplicant" name="name" id="name" value="" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                        </div>
                    </li>
                    <li>
                        <input type="submit" value="X" class="searchForm" id="navClearButton"/>
                    </li>
                    <li>
                        <input type="submit" value="Search" class="searchForm" id="navSubmitButton"/>
                    </li>
                    <li class="pull-right">
                        <label for="stages">
                            Select Stages
                            <select id="stages" class="submitApplicant form-control" name="stageId">
                                <option value="all">All</option>
                            </select>
                        </label>
                    </li>
                    <li class="pull-right">
                        <label for="cohorts">
                            Select Cohort
                            <select id="cohorts" class="submitApplicant form-control" name="cohortId">
                                <option value="all">All</option>
                            </select>
                        </label>
                    </li>
                </ul>

                <div class="tab-content">
                    <?php echo \Portal\ViewHelpers\DisplayApplicantViewHelper::displayApplicantTable($data, $sort); ?>
<!--                    --><?php //echo \Portal\ViewHelpers\DisplayApplicantViewHelper::displayTab($data, 'apprentice', $sort); ?>

                </div>

            </form>
<!--            --><?php //echo \Portal\ViewHelpers\PaginationViewHelper::pagination($page, $count);?>
<!--            --><?php //echo \Portal\ViewHelpers\PaginationViewHelper::pagination($page, $count);?>
        </div>

        <!-- Modal -->
        <?php require('partials/applicantInfoModal.phtml'); ?>
        <?php require('partials/nextStageModal.phtml'); ?>
        <?php require('partials/applicantPasswordModal.phtml'); ?>
    </div>

<?php require 'partials/layout/footer.phtml'; ?>

</body>
</html>