<!DOCTYPE html>
<html>
    <head>
        <?php
        require 'partials/layout/head.phtml';
        echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Authenticate');
        ?>
        <link rel="stylesheet" type="text/css" href="./css/login.css"/>
    </head>
    <body>
        <?php require 'partials/layout/header.phtml'; ?>
        <?php require 'partials/layout/nav.phtml'; ?>
        <main class="login">
                <h1>Authenticate</h1>
                <form id="loginForm" action='/api/authenticatePassword' method='post'>
                    <div class='row justify-content-md-center'>
                        <div class="form-group justify-content-md-center col-lg-4">
                            <input type='number' name='id' value='<?= $id ?>' hidden>
                        </div>
                    </div>
                    <div class='row justify-content-md-center'>
                        <div class="form-group justify-content-md-center col-lg-4">
                            <label for="password">Password</label>
                            <input type="password" name="password" id="password" required class="form-control">
                            <span id="passwordWarning"></span>
                        </div>
                    </div>
                    <div class='row justify-content-md-center'>
                        <div class="form-group justify-content-md-center col-lg-4">
                            <input type="submit" value="Login" id="submit" class="btn btn-success">
                            <span id="submitWarning" class="req"></span>
                        </div>
                    </div>
                    <div id="error-message" class='text-danger'>
                        <?= $_SESSION['authenticationError'] ?>
                    </div>
                </form>
        </main>
        <?php require 'partials/layout/footer.phtml'; ?>
    </body>
</html>
