<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js"></script>
    <script defer src="./js/calendarPage.js"></script>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Calendar');
    ?>
</head>

<body>

<?php require 'partials/layout/header.phtml'; ?>
<?php require 'partials/layout/nav.phtml'; ?>

<div id="calendar"></div>
<?php require 'partials/calendarModal.phtml';?>
<?php require 'partials/layout/footer.phtml'; ?>

</body>

</html>