<!DOCTYPE html>
<html lang="en">

<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Courses');
    ?>
        <script defer src="js/deleteCategory.js"></script>
</head>

<body>
<?php
require 'partials/layout/header.phtml';
require 'partials/layout/nav.phtml';
?>
<div class="container-fluid">
    <div class="row courses-heading-container">
        <div class="col-xs-6 text-left courses-box">
            <h3>Course Category</h3>
        </div>
    </div>
    <table class="col-xs-12 table-bordered table">
        <tr>
            <th class="col-xs-9">Category</th>
            <th class="col-xs-3">Action</th>
        </tr>
        <?php echo Portal\ViewHelpers\CourseCategoriesViewHelper::displayCourseCategories($categories); ?>
    </table>
</div>


<?php
require 'partials/layout/footer.phtml';
?>
</body>

</html>