<!DOCTYPE html>
<html lang="en">

<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Courses');
    ?>
</head>

<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>

        <h3>Courses</h3>
        <div id="courses">
            <table class="col-xs-12 table-bordered table">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>Start Date</td>
                        <td>End Date</td>
                        <td>Course Name</td>
                        <td>Trainer</td>
                        <td>Notes</td>
                    </tr>
                </thead>
                <tbody>
                <?php echo \Portal\ViewHelpers\DisplayCoursesViewHelper::displayCourses($data); ?>
                </tbody>
            </table>
        </div>
<?php require 'partials/layout/footer.phtml'; ?>
</body>