<?php
$successes = $data['successes'] ?? null;
$failures = $data['failures'] ?? null;

?>
<!doctype html>
<html lang="en">
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Document</title>
</head>
<body>

<?php
require 'partials/layout/header.phtml';
require 'partials/layout/nav.phtml';
?>


<form action="/api/csvUpload" method="post" enctype="multipart/form-data">
    <label for="csv">Csv:</label>
    <input id="csv" name="csv" type="file">
    <button class="btn-primary">Submit</button>
</form>

<?php

if ($successes !== null) {
    echo '<p>Result : ' . $successes . ' successfully uploaded records.</p>';
}

if ($failures !== null) {
    if (count($failures) > 0) {
        echo count($failures) . ' unsuccessful uploads: '
            . '<table class="table">'
            . '<thead>'
            . '<tr>'
            . '<th>Name</th>'
            . '<th>Row Number</th>'
            . '</tr>'
            . '</thead>'
            . '<tbody>';
        foreach ($failures as $failure) {
            echo '<tr>'
                . '<td>' . $failure['name'] . '</td>'
                . '<td>' . $failure['row'] . '</td>'
                . '</tr>';
        }
        echo '</tbody>'
            . '</table>';
    }
}
?>

<?php require 'partials/layout/footer.phtml'?>
</body>
</html>