<?php
$successes = $data['successes'];
$failures = $data['failures']

?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<form action="/api/csvUpload" method="post" enctype="multipart/form-data">
    <label for="csv">Csv:</label>
    <input id="csv" name="csv" type="file">
    <button>Submit</button>
</form>

<?php

echo '<p>Result : ' . $successes . ' successfuly uploaded records</p>';

if (count($failures) > 0) {
    echo count($failures) . ' Unsuccesful uploads: '
            . '<table>'
            . '<thead>'
            . '<tr>'
            . '<th>Name</th>'
            . '<th>Row Number</th>'
            . '</tr>'
            . '</thead>'
            . '<tbody>';
    foreach ($failures as $failure) {
        echo '<tr>'
                . '<td>' . $failure['name'] . '</td>'
                . '<td>' . $failure['row'] . '</td>'
                . '</tr>';
    }
    echo '</tbody>'
            . '</table>';
}
?>

</body>
</html>