<?php
$successes = $data['successes'] ?? null;
$failures = $data['failures'] ?? null;

?>
<!doctype html>
<html lang="en">
<head>
    <?php
    require 'partials/layout/head.phtml';
    ?>
    <title>Document</title>
</head>
<body>

<?php
require 'partials/layout/header.phtml';
require 'partials/layout/nav.phtml';
?>

  <h3>Csv upload template</h3>
  <table class="table">
    <thead>
      <tr>
        <th>name</th>
        <th>email</th>
        <th>phoneNumber</th>
        <th>gender</th>
        <th>whyDev</th>
        <th>codeExperience</th>
        <th>hearAboutId</th>
        <th>eligible</th>
        <th>eighteenPlus</th>
        <th>finance</th>
        <th>notes</th>
        <th>backgroundInfoId</th>
        <th>cohort</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Bob</td>
        <td>bob@email.com</td>
        <td>07799555444</td>
        <td>Male</td>
        <td>Lorem ipsum</td>
        <td>Lorem ipsum</td>
        <td>Google</td>
        <td>Yes</td>
        <td>Yes</td>
        <td>No</td>
        <td>Lorem ipsum</td>
        <td>Changing careers</td>
        <td>2022-03-31</td>
      </tr>
    </tbody>
  </table>

  <form action="/api/csvUpload" method="post" enctype="multipart/form-data">
    <label for="csv">Csv:</label>
    <input id="csv" name="csv" type="file" required>
    <button class="btn-primary">Submit</button>
  </form>
<?php

if ($successes !== null) {
    echo '<p>Result : ' . $successes . ' successfully uploaded records.</p>';
}

if ($failures !== null) {
    if (count($failures) > 0) {
        echo count($failures) . ' unsuccessful uploads: '
            . '<table class="table">'
            . '<thead>'
            . '<tr>'
            . '<th>Name</th>'
            . '<th>Row Number</th>'
            . '</tr>'
            . '</thead>'
            . '<tbody>';
        foreach ($failures as $failure) {
            echo '<tr>'
                . '<td>' . $failure['name'] . '</td>'
                . '<td>' . $failure['row'] . '</td>'
                . '</tr>';
        }
        echo '</tbody>'
            . '</table>';
    }
}
?>

<?php require 'partials/layout/footer.phtml'?>
</body>
</html>