<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>Registered Applicants</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/displayApplicants.css">
    <link rel="stylesheet" type="text/css" href="/css/genericStyles.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script defer src="js/applicantModal.js"></script>

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 registeredApplicants">
                <h1 class="col-xs-12 applicantFields">Registered Applicants</h1>
<!--                this needs checking with viewHelper when all relevant branches are merged-->
                <?php echo \Portal\ViewHelpers\DisplayApplicantViewHelper::displayApplicants($data); ?>
            </div>
            <div class="container">
                <!-- Trigger the modal with a button -->
                <a type="button"  id="myBtn">Applicant name(modal)</a>
                <!-- Modal -->
                <div class="modal fade" id="myModal" role="dialog">
                    <div class="modal-dialog">

                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h2 class="modal-title">Applicant Details</h2>
                            </div>
                            <div class="modal-body">
                                <h3>Personal Information</h3>
                                <h4>Name</h4>
                                <h4>Email</h4>
                                <h4>Phone Number</h4>
                            </div>
                            <hr>
                            <div class="modal-body">
                                <h3>Application Information</h3>
                                <h4>Cohort</h4>
                                <h4>Reason for wanting to be a dev</h4>
                                <h4>Code Experience</h4>
                                <h4>Heard About Us</h4>
                                <h4>Eligibility</h4>
                                <h4>18+ </h4>
                                <h4>Finance</h4>
                                <h4>Notes</h4>
                                <h4>Date/Time Added</h4>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a href="/admin"></a>
        </div>
    </div>
</body>
</html>
