<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Edit Applicant Stages');
    ?>
    <link href="css/stages.css" rel="stylesheet" type="text/css">
    <script defer src="./js/Sortable.js"></script>
    <script defer src="./js/stagesPage.js"></script>
    <script defer src="./js/stageReorder.js"></script>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>
    <main>
        <div class="applicantStages">
            <p class="stagesInstruction">Drag a stage to change the order</p>
            <div id="editResponse" class="text-danger"></div>
            <table class="table-bordered table">
                <tbody id="stageTable" class="list-group">
                <?php echo \Portal\ViewHelpers\StagesPageViewHelper::displayStages($data); ?>
                </tbody>
            </table>
            <p class="stagesInstruction">Add a new stage:</p>
            <form action="/api/createStage" method="post" id="newStageForm">
                <input type="text" class="col-xs-7" placeholder="Type new stage" name="createNewStageTextBox"/>
                <input type="submit" class="btn-success" value="Submit"/>
            </form>
            <div id="createNewResponse" class="text-danger"></div>
        </div>
    </main>
<?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>