<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Edit Applicant Stages');
    ?>
    <link href="css/stages.css" rel="stylesheet" type="text/css">
    <script defer src="./js/Sortable.js"></script>
    <script defer src="./js/stagesPage.js"></script>
    <script defer src="./js/stageReorder.js"></script>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>
    <main>
        <div class="applicantStages">
            <div class="addStage">
                <h3 class="stagesInstruction">Add a new stage</h3>
                <form action="/api/createStage" method="post" id="newStageForm" class="form-inline">
                    <div>
                        <label>
                            Student stage:
                            <input type="checkbox" name="student">
                            <i class="glyphicon glyphicon-education text-success"></i>
                        </label>
                    </div>
                    <input type="text" class="form-control" placeholder="Stage Name" name="createNewStageTextBox"/>
                    <input type="submit" class="btn-success btn" value="Save"/>
                </form>
                <div id="createNewResponse" class="text-danger"></div>
            </div>
            <div class="editStages">
                <h3>Edit stages</h3>
                <p>Drag a stage to change the order</p>
                <div id="editResponse" class="text-danger"></div>
                <table class="table">
                    <tbody id="stageTable" class="list-group">
                    <?php echo \Portal\ViewHelpers\StagesPageViewHelper::displayStages($data); ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>

<div class="modalContainer hidden">
    <div class="container">
        <div class="body">
            <p>Warning: Deleting this option will delete all options from this stage.
            Click "Delete All Options" to proceed</p>
            <a class="closeModal">Cancel</a>
            <a class="deleteAllOptions text-danger delete">Delete All Options</a>
        </div>
    </div>
</div>
<?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>