<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Edit Applicant Stages');
    ?>
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" data-auto-a11y="true" ></script>
    <link href="css/stages.css" rel="stylesheet" type="text/css">
    <link href="css/stageDeletionModal.css" rel="stylesheet" type="text/css">
    <script defer src="./js/Sortable.js"></script>
    <script defer src="./js/stagesPage.js"></script>
    <script defer src="./js/stageReorder.js"></script>
    <script defer src="./js/stageDeletionModal.js"></script>
<!--enabling all tooltips in the document-->
    <script>$(document).ready(function() {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>

    <main>
        <button class="thingy">Click me please</button>
        <button class="thingy">Click me please</button>
        <div class="applicantStages">
            <div class="addStage">
                <h3 class="stagesInstruction">Add a new stage</h3>
                <form action="/api/createStage" method="post" id="newStageForm" class="form-inline">
                    <div>
                        <label for="stages">Select Stage Flag: </label>
                        <select name="stages" id="stages">
                            <option name="notAssigned">Not assigned</option>
                            <option name="student">Student</option>
                            <option name="withdrawn">Withdrawn</option>
                            <option name="rejected">Rejected</option>
                        </select>
                    </div>
                    <input type="text" class="form-control" placeholder="Stage Name" name="createNewStageTextBox"/>
                    <input type="submit" class="btn-success btn" value="Add"/>
                </form>
                <div id="createNewResponse" class="text-danger"></div>
            </div>
            <div class="editStages">
                <h3>Edit stages</h3>
                <p>Drag a stage to change the order</p>
                <div id="editResponse" class="text-danger"></div>
                <table class="table">
                    <tbody id="stageTable" class="list-group">
                    <?php echo \Portal\ViewHelpers\StagesPageViewHelper::displayStages($data); ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>

<div class="modalContainer" hidden>
    <div class="container">
        <div class="body">
            <p>Warning: Deleting this option will delete all options from this stage.
            Click "Delete All Options" to proceed</p>
            <a class="closeModal">Cancel</a>
            <a class="deleteAllOptions text-danger delete">Delete All Options</a>
        </div>
    </div>
</div>

<?php require 'partials/allowStageDeletionModal.phtml'; ?>
<?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>