<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Events</title>
    <link rel="stylesheet" type="text/css" href="css/genericStyles.css"/>
    <link rel="stylesheet" type="text/css" href="css/eventList.css">
    <script defer src="js/eventList.js"></script>
</head>
<body>
    <main>
        <h1 id="eventTitle">Events</h1>
        <div class="event">
            <div class="top">
                <div class="upper">
                    <div class="infoBox">
                        <span><strong>Name</strong></span>
                        <span>June Taster Session</span>
                    </div>
                    <div class="infoBox">
                        <span><strong>Type</strong></span>
                        <span>Taster Session</span>
                    </div>
                    <div class="infoBox">
                        <span><strong>Date</strong></span>
                        <span>23/06/2019</span>
                    </div>
                </div>
                <div class="mid">
                    <div class="infoBox-mid">
                        <span><strong>Start Time</strong></span>
                        <span>18:00</span>
                    </div>
                    <div class="infoBox-mid">
                        <span><strong>End Time</strong></span>
                        <span>22:00</span>
                    </div>
                </div>
            </div>
            <div class="arrowBox">
                <span>&#x21E9;</span>
            </div>
            <div class="lower">
                <div class="infoBox-low">
                    <span><strong>Location</strong></span>
                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
                </div>
                <div class="infoBox-low">
                    <span><strong>Notes</strong></span>
                    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </div>
                </div>
            </div>
        </div>
        <div class="addButtonWrapper">
            <a href="/admin" class="addButton">Back</a>
        </div>
    </main>
</body>
</html>