<!DOCTYPE html>
<html lang="en">

<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Events');
    ?>
    <link href="css/events.css" rel="stylesheet" type="text/css">
    <script defer src="./js/validations.js"></script>
    <script defer src='./js/eventsPage.js'></script>
</head>

<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>
        <h2>Add new Event</h2>
        <form id='create-events-form'>
            <label for='event-category'>Event category</label>
            <select name='event-category' id='event-category' class='create-events form-control'>
                <option value='0'>Select an event category</option>
                <?php echo \Portal\ViewHelpers\EventCategoryViewHelper::eventCategoryDropdown($data); ?>
            </select>

            <label for="event-name">Event Name</label>
            <input id="event-name" name="event-name" class="create-events form-control" type="text" placeholder="Event Name" data-required='true' data-max='255' maxlength="255">

            <label for='event-date'>Date</label>
            <input id="event-date" name="event-date" class="create-events form-control" type="date" data-required='true'>

            <label for="event-location">Location</label>
            <input id="event-location" name="event-location" class="create-events form-control" type="text" placeholder="Location" data-required='true' data-max='255' maxlength="255">

            <label for='event-start-time'>Event Start Time</label>
            <input id='event-start-time' name='event-start-time' class="create-events form-control" type="time" data-required='true'>

            <label for='event-end-time'>Event End Time</label>
            <input id='event-end-time' name='event-end-time' class="create-events form-control" type="time" data-required='true'>

            <label for='event-notes'>Notes</label>
            <input id='event-notes' name='event-notes' class="create-events form-control" type="text" placeholder="Notes" data-max='5000' maxlength='5000'>

            <input id="submit-event" type="submit" class="btn btn-success" />
        </form>
        <div id='messages'></div>
        <div>
            <h2>Search Events</h2>
            <input id="academy-events-search" name="search-event-input" type="text" maxlength="255">
            <input class="btn btn-success" id="submit-search-event" value="Search" type="submit">
            <a id="clear-search" class="btn btn-warning" href="./displayEventsPage">Clear Search</a>
        </div>
        <h2 id="events-list">Current Events</h2>
        <div id='events'></div>
<?php require 'partials/layout/footer.phtml'; ?>
</body>