<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Admin Login</title>
    <link rel="stylesheet" type="text/css" href="css/genericStyles.css"/>
    <link rel="stylesheet" type="text/css" href="css/eventList.css">
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script defer src="js/eventList.js"></script>
</head>
<body>
    <main>
        <h2 id="eventTitle">Events</h2>
        <div class="event">
            <div class="top">
                <div class="upper">
                    <div class="infoBox">
                        <span><strong>Name</strong></span>
                        <span >Boobies</span>
                    </div>
                    <div class="infoBox">
                        <span><strong>Type</strong></span>
                        <span>Taster Session</span>
                    </div>
                    <div class="infoBox">
                        <span><strong>Date</strong></span>
                        <span>23/06/2019</span>
                    </div>
                </div>

                <div class="mid">
                    <div class="infoBox-mid">
                        <span><strong>Start Time</strong></span>
                        <span>18:00</span>
                    </div>
                    <div class="infoBox-mid">
                        <span><strong>End Time</strong></span>
                        <span>22:00</span>
                    </div>
                </div>
            </div>
            <div class="arrowBox">
                <span>&#x21E9;</span>
            </div>
            <div class="lower">
                <div class="infoBox-low">
                    <span><strong>Location</strong></span>
                <div> down the end of the road turn left turn right turn left turn right turn left turn right turn left turn right turn left turn right turn left turn right and youre there </div>
                </div>
                <div class="infoBox-low">
                    <span><strong>Notes</strong></span>
                    <div>so you ahve to enter this whole domain of something down in the mug of doom now if we enter this mug of odom then we ca open the yellow gate of magic, this will grant you the power of inivisibilty.</div>
                </div>
            </div>

        </div>
        <div class="event">
            <div class="top">
                <div class="upper">
                    <div class="infoBox">
                        <span><strong>Name</strong></span>
                        <span >Boobies</span>
                    </div>
                    <div class="infoBox">
                        <span><strong>Type</strong></span>
                        <span>Taster Session</span>
                    </div>
                    <div class="infoBox">
                        <span><strong>Date</strong></span>
                        <span>23/06/2019</span>
                    </div>
                </div>

                <div class="mid">
                    <div class="infoBox-mid">
                        <span><strong>Start Time</strong></span>
                        <span>18:00</span>
                    </div>
                    <div class="infoBox-mid">
                        <span><strong>End Time</strong></span>
                        <span>22:00</span>
                    </div>
                </div>
            </div>
            <div class="arrowBox">
                <span>&#x21E9;</span>
            </div>
            <div class="lower hidden">
                <div class="infoBox-low">
                    <span><strong>Location</strong></span>
                    <div> down the end of the road turn left turn right turn left turn right turn left turn right turn left turn right turn left turn right turn left turn right and youre there </div>
                </div>
                <div class="infoBox-low">
                    <span><strong>Notes</strong></span>
                    <div>so you ahve to enter this whole domain of something down in the mug of doom now if we enter this mug of odom then we ca open the yellow gate of magic, this will grant you the power of inivisibilty.</div>
                </div>
            </div>

        </div>


    </main>
</body>
</html>