<!DOCTYPE html>
<html lang="en">

<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Events');
    ?>
    <script defer src='./js/eventsPage.js' type="module"></script>

</head>

<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>
    <div>
        <h4>Search <?=$eventType?> Events</h4>
        <input id="academy-events-search" name="search-event-input" type="text" maxlength="255">
        <select style="height: 26px" name="categories" id="categoriesFilter">
            <option value="">Filter by Category</option>
        </select>
        <input class="btn btn-success" id="submit-search-event" value="Search" type="submit">
        <a id="clear-search" class="btn btn-warning" href="./events">Clear Search</a>
        <div class="alert" id="messages"></div>
    </div>
        <h3 id="events-list" data-event-type="<?=$eventType?>"><?=$eventType?> Events</h3>
    <div id='events'></div>
<div id="pageNumberDisplay">
    <a id="counterMinus">previous </a>
    <a id="buttonOne"></a>
    <a id="buttonTwo"></a>
    <a id="buttonThree"></a>
    <span id="dots"></span>
    <a id="counterPlus"> next</a>
</div>

    <?php require('partials/applicantInfoModal.phtml'); ?>
    <?php require 'partials/layout/footer.phtml'; ?>
</body>