<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>Academy Events</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="./css/genericStyles.css">
    <script defer src='./js/eventsPage.js'></script>
</head>

<body>
    <div class="container">
        <h1>Events</h1>
        <button type="button" class="btn btn-success">Go Back To Admin Page</button>
        <h2>Add new Event</h2>
        <form id='create-events-form'>
            <label for='event-category'>Event category</label>
            <select name='event-category' id='event-category' class='create-events form-control'>
                <option value='0'>Select and event category</option>
                <?php echo \Portal\ViewHelpers\EventCategoryViewHelper::eventCategoryDropdown($data); ?>
            </select>

            <label for="event-name">Event Name</label>
            <input id="event-name" name="event-name" class="create-events form-control" type="text" placeholder="Event Name" data-required='true' data-max='255' maxlength="255">

            <label for='event-date'>Date</label>
            <input id="event-date" name="event-date" class="create-events form-control" type="date" data-required='true'>

            <label for="event-location">Location</label>
            <input id="event-location" name="event-location" class="create-events form-control" type="text" placeholder="Location" data-required='true' data-max='255' maxlength="255">

            <label for='event-start-time'>Event Start Time</label>
            <input id='event-start-time' name='event-start-time' class="create-events form-control" type="time" data-required='true'>

            <label for='event-end-time'>Event End Time</label>
            <input id='event-end-time' name='event-end-time' class="create-events form-control" type="time" data-required='true'>

            <label for='event-notes'>Notes</label>
            <input id='event-notes' name='event-notes' class="create-events form-control" type="text" placeholder="Notes" data-max='5000' maxlength='5000'>

            <input id="submit-event" type="submit" class="btn btn-success" />
        </form>
        <div id='messages'></div>
        <h3>Current Events</h3>
        <div id='events'></div>
    </div>
</body>