<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Admin Login</title>
    <link rel="stylesheet" type="text/css" href="css/genericStyles.css"/>
    <link rel="stylesheet" type="text/css" href="css/eventList.css">
    <script defer src="js/eventList.js"></script>
</head>
<body>
    <main>
        <h1 id="eventTitle">Events</h1>
        <?php $eventListData = \Portal\ViewHelpers\EventListViewHelper::outputEventList($events);
        foreach ($eventListData as $i){echo $i;}?>
        <div class="addButtonWrapper">
            <a href="/admin" class="addButton">Back</a>
        </div>
    </main>
</body>
</html>