<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Academy Portal | Hiring Partners</title>
    <link type="text/css" rel="stylesheet" href="./css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="./css/genericStyles.css">
</head>
<body>
    <div class="container">
        <h1>Hiring Partners</h1>
        <form>
            <label for="name">Company Name</label>
            <input id="name" name="name" class="submitHiringPartner form-control" type="text" placeholder="name" required>
            <label for='companySize'>Company Size</label>
            <select name='companySize' id='companySize' class='form-control'>
                <?php echo \Portal\ViewHelpers\CompanySizeViewHelper::companySizeDropdown($data); ?>
            </select>
            <label for="techStack">Company Tech Stack</label>
            <input id="techStack" name="techStack" class="submitHiringPartner form-control" type="text" placeholder="Company tech stack" required>
            <label for='postcode'>Postcode</label>
            <input id='postcode' name='postcode' class="submitHiringPartner form-control" type="text" placeholder="Postcode" required>
            <label for='phoneNumber'>Phone Number</label>
            <input id='phoneNumber' name='phoneNumber' class="submitHiringPartner form-control" type="text" placeholder="Phone Number">
            <label for='companyUrl'>Company Website URL</label>
            <input id='companyUrl' name='companyUrl' class="submitHiringPartner form-control" type="text" placeholder="Company Website Url">
            <input id="submitHiringPartner" type="submit" class="btn btn-success"/>
        </form>
    </div>
</body>