<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Admin Login</title>
        <link rel="stylesheet" type="text/css" href= "../public/css/style.css"/>
        <script src="../public/js/loginValidation.js" defer></script>
    </head>
    <body>
        <h1>Login</h1>
        <form id="formID" class="text-input-field">
            <div>
                <input type="text" name="userEmail" id="userEmail">
                <label for="userEmail">User Email (Required)</label>
                <span id="userEmailWarning" class="req"></span>
            </div>
            <div>
                <input type="text" name="password" id="password">
                <label for="password">Password (Required)</label>
                <span id="passwordWarning" class="req"></span>
            </div>
            <div>
                <input type="submit" value="Login" id="submit" class="submit">
                <span id="submitWarning" class="req"></span>
            </div>
        </form>

    </body>
</html>
