<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Admin Login</title>
        <link rel="stylesheet" type="text/css" href="css/style.css"/>
        <script src="js/loginValidation.js" defer></script>
    </head>
    <body>
        <h1>Login</h1>
        <form id="loginForm" class="text-input-field">
            <div>
                <input type="email" name="userEmail" id="userEmail" required>
                <label for="userEmail">User Email (Required)</label>
                <span id="userEmailWarning" class=""></span>
            </div>
            <div>
                <input type="password" name="password" id="password" required>
                <label for="password">Password (Required)</label>
                <span id="passwordWarning" class=""></span>
            </div>
            <div>
                <input type="submit" value="Login" id="submit" class="submit">
                <span id="submitWarning" class="req"></span>
            </div>
        </form>
    </body>
</html>
