<!doctype html>
<html lang="en">
<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Register User');
    ?>

    <script src='js/passwordRandom.js' defer></script>
    <script src='js/registerUser.js' defer></script>
    <link rel="stylesheet" href="./css/admin.css">
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>
    <h1> Registration Page</h1>
    <div id="message"></div>
    <form id="registerUserForm">
        <div>
            <h4>Password</h4>
            <input type="text" id="randomPassword" readonly value="<?php echo $password;?>">
        </div>
    <div>
        <h4>Email
        </h4>
        <input id="emailNewUser" type="email" name="email">
        <input type="submit" id="newUserSubmit">
        </div>
    </form>
<?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>