<!doctype html>
<html lang="en">
<head>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Register User');
    ?>
    <script src='js/registerUser.js' defer></script>
    <link rel="stylesheet" href="./css/registerUser.css">
</head>
<body>
<?php require 'partials/layout/header.phtml'; ?>

<?php require 'partials/layout/nav.phtml'; ?>
    <h3>Register User</h3>
    <form id="registerUserForm">
        <div class="form-group">
            <label for="randomPassword">Password</label>
            <input type="text" id="randomPassword" class="form-control" readonly value="<?php echo $password;?>">
        </div>
        <div class="form-group">
            <label for="emailNewUser">Email</label>
            <input id="emailNewUser" class="form-control" type="email" name="email">
        </div>
        <div class="form-group">
            <p class="text-danger">Remember to save the password before creating the user.</p>
            <input type="submit" id="newUserSubmit" class="btn btn-success" value="Register">
            <div id="message" class="alert"></div>
        </div>
    </form>
<?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>