<head>
    <script src='js/passwordRandom.js' defer></script>
    <script src='js/registerUser.js' defer></script>
    <link rel="stylesheet" href="css/admin.css">
    <title>AcademyPortal | Register User</title>
</head>

<h1> Registration Page</h1>

<form id="registerUserForm">
    Password<input id="randomPassword" type="text" name="password">
    <br>
    Email<input id="emailNewUser" type="email" name="email">
    <input type="submit">
</form>

<div id="message">
</div>

<a href="/admin" class="returnButton">Return to admin page</a>