<!DOCTYPE html>
<html>
    <head>
        <?php
        require 'partials/layout/head.phtml';
        echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Login');
        ?>
        <link rel="stylesheet" type="text/css" href="../css/login.css"/>
    </head>
    <body>
        <div class="container">
            <header>
                <div class="logo pull-right"><img src="https://dev.io-academy.uk/logo.svg" alt="iO Academy"></div>
            </header>
        </div>
        <main class="login">
            <h1>Login</h1>
            <form method="post" id="loginForm">
                <div class="form-group">
                    <label for="password">Password (Required)</label>
                    <input type="password" name="password" id="password" required class="form-control">
                    <span id="passwordWarning"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Login" id="submit" class="btn btn-success">
                    <span id="submitWarning" class="req"></span>
                </div>
                <div id="error-message"></div>
            </form>
        </main>
        <?php require 'partials/layout/footer.phtml'; ?>
    </body>
</html>
