<?php

use Portal\ViewHelpers\StudentApplicationFormViewHelper;

$pages = 5;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="css/studentApplicationForm.css" rel="stylesheet">
    <title>Your Application</title>
    <script src="./js/validations.js" defer></script>
    <script src="./js/saveApplicant.js" defer></script>
<!--    <script src="./js/applicantForm.js" defer></script>-->
    <script defer src="./js/studentApplicationForm.js"></script>
</head>
<body>
<div>
    <h1> Your Application</h1>
    <p >Page <span id="pageCounter">1</span> of <?php echo $pages ?></p>
    <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5" style="width: 0%"></div> <!-- REPLACE WITH SCSS TO CALC PAGE PROGRESS-->
    </div>
    <form id="studentApplicationForm" method="post">
        <?php echo StudentApplicationFormViewHelper::displayform($pages, $dropDownData) ?>
    </form>
</div>
</body>
</html>
