<?php

use Portal\ViewHelpers\StudentApplicationFormViewHelper;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your Application</title>
    <script src="./js/validations.js" defer></script>
    <script src="./js/saveApplicant.js" defer></script>
    <script src="./js/applicantForm.js" defer></script>
</head>
<body>
<div>
    <h1> Your Application</h1>
    <p>Step X of Y</p> <!--    REPLACE WITH PAGE NUMBERS-->
    <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5" style="width: 0%"></div> <!-- REPLACE WITH SCSS TO CALC PAGE PROGRESS-->
    </div>
    <form>
        <?php echo StudentApplicationFormViewHelper::displayPageByNumber($pageNumber, $dropDownData); ?>
    </form>
    <?php echo StudentApplicationFormViewHelper::displayNextButtons($pageNumber, 5); ?>
</div>
</body>
</html>
