<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script src="js/addHiringPartner.js" defer></script>
</head>
<body>

<form>
    <div class="formField">
        <input type="text" name="companyName" class="field" data-required="true"/>
    </div>

    <div class="formField">
        <select name="size" class="field" data-required="true">
            <option value="">Please select</option>
            <option value="1"><5</option>
            <option value="2">5-10</option>
            <option value="3">11-25</option>
            <option value="4">26-50</option>
        </select>
    </div>

    <div class="formField">
        <input type="text" name="postcode" class="field" data-required="true" data-postcode="true"/>
    </div>

    <input type="submit"/>
</form>

<p class="statusMessage"></p>

</body>
</html>