<!DOCTYPE html>
<html lang="en">

<head>
    <script defer src="/js/displaytrainers.js"></script>
    <script defer src="/js/trainerNotesModal.js"></script>
    <script defer src="/js/cookies.js"></script>
    <?php
    require 'partials/layout/head.phtml';
    echo \Portal\ViewHelpers\LayoutViewHelper::outputTitle('Trainers');
    ?>
</head>
<body>
    <?php require 'partials/layout/header.phtml'; ?>
    <?php require 'partials/layout/nav.phtml'; ?>

    <h1>Trainers</h1>  
    <div id="trainers" class="row">
        <div id="editResponse" class="text-danger"></div>
            <table class="col-xs-12 table-bordered table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                <?= \Portal\ViewHelpers\TrainerTableViewHelper::displayTrainerTable($trainers); ?>
                </tbody>
            </table>
        </div>
    <?php require('partials/trainerNotesModal.phtml'); ?>     
    <?php require 'partials/layout/footer.phtml'; ?>
</body>
</html>