<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>AcademyPortal | Admin</title>
        <link rel="stylesheet" type="text/css" href="css/genericStyles.css"/>
        <link rel="stylesheet" href="css/admin.css">
    </head>
    <body>
        <h1> Admin Page</h1>
        <a href="/register" class="addUserButton">Add User</a>
        <a href="/addapplicant" class="addUserButton">Register Applicant</a>
        <a href="/displayApplicants" class="addUserButton">Display Applicants</a>
    </body>
</html>
