<div class="container">
    <header>
        <div class="external-links pull-left">
            <a href="http://mayden.academy" target="_blank">
                <i class="glyphicon glyphicon-globe"></i>
                <div>Website</div>
            </a>
            <a href="https://dev.maydenacademy.co.uk/projects/aptitude-test/app/" target="_blank">
                <i class="glyphicon glyphicon-list-alt"></i>
                <div>Apt Test</div>
            </a>
            <a href="https://drive.google.com/drive/folders/0AFB6MvsmFGWZUk9PVA" target="_blank">
                <i class="glyphicon glyphicon-folder-open"></i>
                <div>G Drive</div>
            </a>
        </div>

        <div class="logo pull-right"><img src="https://mayden.academy/wp-content/themes/academy3/images/logo-academy.svg" alt="Mayden Academy"></div>
    </header>