<div class="container">
    <header>
        <div class="external-links pull-left">
            <a href="https://io-academy.uk/" target="_blank">
                <i class="glyphicon glyphicon-globe"></i>
                <div>Website</div>
            </a>
            <a href="https://aptitude-test.io-academy.uk/" target="_blank">
                <i class="glyphicon glyphicon-list-alt"></i>
                <div>Apt Test</div>
            </a>
            <a href="https://drive.google.com/drive/folders/0AFB6MvsmFGWZUk9PVA" target="_blank">
                <i class="glyphicon glyphicon-folder-open"></i>
                <div>G Drive</div>
            </a>
        </div>

        <div class="logo pull-right"><img src="https://dev.io-academy.uk/logo.svg" alt="iO Academy"></div>
    </header>