<nav class="btn-group" role="group">
    <a href="/admin" class="btn btn-default">Home</a>

    <div class="btn-group">
        <a href="/applicants" class="btn btn-default">Applicants</a>
        <button type="button" class="btn dropdown-toggle btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="/addapplicant">New Applicant</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/teamPicker">Team Picker</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/editStages">Edit Applicant Stages</a></li>
        </ul>
    </div>

    <div class="btn-group">
        <a href="/events" class="btn btn-default">Events</a>
        <button type="button" class="btn dropdown-toggle btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="/addEvent">New Event</a></li>
            <li><a href="/events-past">Past Events</a></li>
        </ul>
    </div>

    <div class="btn-group">
        <a href="/hiringPartners" class="btn btn-default">Hiring Partners</a>
        <button type="button" class="btn dropdown-toggle btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="/addHiringPartner">New Hiring Partner</a></li>
            <li><a href="/addHiringPartnerContact">New Hiring Partner Contact</a></li>
        </ul>
    </div>

    <div class="btn-group">
        <a href="/courses" class="btn btn-default">Courses</a>
        <button type="button" class="btn dropdown-toggle btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="/addCourse">Add New Course</a></li>
        </ul>
    </div>

</nav>